# TESTING PIZZATIME

## Allauth
Installed using command `pip3 install django-allauth`, setup using Allauth documentation and tested by running a server and accessing http://localhost:8000/accounts/login/. By changing `LOGIN_REDIRECT_URL = '/success'` in project folder's settings.py, I could see that login procedure was successful.

